// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type {
	DeleteDefinitionsByIdData,
	DeleteDefinitionsByIdErrors,
	DeleteDefinitionsByIdResponses,
	GetDefinitionsByIdData,
	GetDefinitionsByIdErrors,
	GetDefinitionsByIdResponses,
	GetDefinitionsData,
	GetDefinitionsDomainPoliciesData,
	GetDefinitionsDomainPoliciesErrors,
	GetDefinitionsDomainPoliciesResponses,
	GetDefinitionsErrors,
	GetDefinitionsResponses,
	GetDirectivesData,
	GetDirectivesErrors,
	GetDirectivesResponses,
	GetDomainsData,
	GetDomainsErrors,
	GetDomainsResponses,
	PostDefinitionsByIdMoveData,
	PostDefinitionsByIdMoveErrors,
	PostDefinitionsByIdMoveResponses,
	PostDefinitionsCreateFromFrontendData,
	PostDefinitionsCreateFromFrontendErrors,
	PostDefinitionsCreateFromFrontendResponses,
	PostDefinitionsSaveData,
	PostDefinitionsSaveErrors,
	PostDefinitionsSaveResponses,
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Definitions {
	public static getDefinitions<ThrowOnError extends boolean = true>(
		options?: Options<GetDefinitionsData, ThrowOnError>,
	): RequestResult<GetDefinitionsResponses, GetDefinitionsErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetDefinitionsResponses, GetDefinitionsErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions',
			...options,
		});
	}

	public static deleteDefinitionsById<ThrowOnError extends boolean = true>(
		options: Options<DeleteDefinitionsByIdData, ThrowOnError>,
	): RequestResult<DeleteDefinitionsByIdResponses, DeleteDefinitionsByIdErrors, ThrowOnError> {
		return (options.client ?? client).delete<DeleteDefinitionsByIdResponses, DeleteDefinitionsByIdErrors, ThrowOnError>(
			{
				security: [{ scheme: 'bearer', type: 'http' }],
				url: '/umbraco/csp/api/v1/Definitions/{id}',
				...options,
			},
		);
	}

	public static getDefinitionsById<ThrowOnError extends boolean = true>(
		options: Options<GetDefinitionsByIdData, ThrowOnError>,
	): RequestResult<GetDefinitionsByIdResponses, GetDefinitionsByIdErrors, ThrowOnError> {
		return (options.client ?? client).get<GetDefinitionsByIdResponses, GetDefinitionsByIdErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions/{id}',
			...options,
		});
	}

	public static postDefinitionsByIdMove<ThrowOnError extends boolean = true>(
		options: Options<PostDefinitionsByIdMoveData, ThrowOnError>,
	): RequestResult<PostDefinitionsByIdMoveResponses, PostDefinitionsByIdMoveErrors, ThrowOnError> {
		return (options.client ?? client).post<PostDefinitionsByIdMoveResponses, PostDefinitionsByIdMoveErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions/{id}/move',
			...options,
		});
	}

	public static postDefinitionsCreateFromFrontend<ThrowOnError extends boolean = true>(
		options?: Options<PostDefinitionsCreateFromFrontendData, ThrowOnError>,
	): RequestResult<PostDefinitionsCreateFromFrontendResponses, PostDefinitionsCreateFromFrontendErrors, ThrowOnError> {
		return (options?.client ?? client).post<
			PostDefinitionsCreateFromFrontendResponses,
			PostDefinitionsCreateFromFrontendErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions/create-from-frontend',
			...options,
		});
	}

	public static getDefinitionsDomainPolicies<ThrowOnError extends boolean = true>(
		options?: Options<GetDefinitionsDomainPoliciesData, ThrowOnError>,
	): RequestResult<GetDefinitionsDomainPoliciesResponses, GetDefinitionsDomainPoliciesErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			GetDefinitionsDomainPoliciesResponses,
			GetDefinitionsDomainPoliciesErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions/domain-policies',
			...options,
		});
	}

	public static postDefinitionsSave<ThrowOnError extends boolean = true>(
		options: Options<PostDefinitionsSaveData, ThrowOnError>,
	): RequestResult<PostDefinitionsSaveResponses, PostDefinitionsSaveErrors, ThrowOnError> {
		return (options.client ?? client).post<PostDefinitionsSaveResponses, PostDefinitionsSaveErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Definitions/save',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers,
			},
		});
	}
}

export class Directives {
	public static getDirectives<ThrowOnError extends boolean = true>(
		options?: Options<GetDirectivesData, ThrowOnError>,
	): RequestResult<GetDirectivesResponses, GetDirectivesErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetDirectivesResponses, GetDirectivesErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Directives',
			...options,
		});
	}
}

export class Domains {
	public static getDomains<ThrowOnError extends boolean = true>(
		options?: Options<GetDomainsData, ThrowOnError>,
	): RequestResult<GetDomainsResponses, GetDomainsErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetDomainsResponses, GetDomainsErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/csp/api/v1/Domains',
			...options,
		});
	}
}
