// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'https://localhost:44370/' | (string & {});
};

export type CspApiDefinition = {
	id: string;
	enabled: boolean;
	reportOnly: boolean;
	isBackOffice: boolean;
	domainKey?: null | string;
	domainName?: null | string;
	rootContentKey?: null | string;
	disabledDomainPolicyBehavior?: null | DisabledDomainPolicyBehavior;
	reportingDirective?: null | string;
	reportUri?: null | string;
	upgradeInsecureRequests: boolean;
	sources: Array<CspApiDefinitionSource>;
};

export type CspApiDefinitionSource = {
	definitionId: string;
	source: string;
	directives: Array<string>;
};

export type CspApiDomainPolicy = {
	id: string;
	domainKey: string;
	domainName?: null | string;
	enabled: boolean;
	isOrphaned: boolean;
};

export type CspDomainInfo = {
	key: string;
	name: string;
	culture?: null | string;
	rootContentKey?: null | string;
	rootContentName?: null | string;
	hasCspPolicy: boolean;
	cspDefinitionId?: null | string;
};

export type DisabledDomainPolicyBehavior = number;

export type ProblemDetails = {
	type?: null | string;
	title?: null | string;
	status?: null | number | string;
	detail?: null | string;
	instance?: null | string;
};

export type GetDefinitionsData = {
	body?: never;
	path?: never;
	query?: {
		isBackOffice?: boolean;
		domainKey?: string;
	};
	url: '/umbraco/csp/api/v1/Definitions';
};

export type GetDefinitionsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetDefinitionsResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type GetDefinitionsResponse = GetDefinitionsResponses[keyof GetDefinitionsResponses];

export type DeleteDefinitionsByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/csp/api/v1/Definitions/{id}';
};

export type DeleteDefinitionsByIdErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type DeleteDefinitionsByIdError = DeleteDefinitionsByIdErrors[keyof DeleteDefinitionsByIdErrors];

export type DeleteDefinitionsByIdResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type PostDefinitionsByIdMoveData = {
	body?: never;
	path: {
		id: string;
	};
	query?: {
		domainKey?: string;
	};
	url: '/umbraco/csp/api/v1/Definitions/{id}/move';
};

export type PostDefinitionsByIdMoveErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type PostDefinitionsByIdMoveError = PostDefinitionsByIdMoveErrors[keyof PostDefinitionsByIdMoveErrors];

export type PostDefinitionsByIdMoveResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type PostDefinitionsByIdMoveResponse = PostDefinitionsByIdMoveResponses[keyof PostDefinitionsByIdMoveResponses];

export type GetDefinitionsByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/csp/api/v1/Definitions/{id}';
};

export type GetDefinitionsByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetDefinitionsByIdResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type GetDefinitionsByIdResponse = GetDefinitionsByIdResponses[keyof GetDefinitionsByIdResponses];

export type PostDefinitionsCreateFromFrontendData = {
	body?: never;
	path?: never;
	query?: {
		domainKey?: string;
	};
	url: '/umbraco/csp/api/v1/Definitions/create-from-frontend';
};

export type PostDefinitionsCreateFromFrontendErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type PostDefinitionsCreateFromFrontendError =
	PostDefinitionsCreateFromFrontendErrors[keyof PostDefinitionsCreateFromFrontendErrors];

export type PostDefinitionsCreateFromFrontendResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type PostDefinitionsCreateFromFrontendResponse =
	PostDefinitionsCreateFromFrontendResponses[keyof PostDefinitionsCreateFromFrontendResponses];

export type GetDefinitionsDomainPoliciesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Definitions/domain-policies';
};

export type GetDefinitionsDomainPoliciesErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetDefinitionsDomainPoliciesResponses = {
	/**
	 * OK
	 */
	200: Array<CspApiDomainPolicy>;
};

export type GetDefinitionsDomainPoliciesResponse =
	GetDefinitionsDomainPoliciesResponses[keyof GetDefinitionsDomainPoliciesResponses];

export type PostDefinitionsSaveData = {
	body: CspApiDefinition;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Definitions/save';
};

export type PostDefinitionsSaveErrors = {
	/**
	 * Bad Request
	 */
	400: ProblemDetails;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type PostDefinitionsSaveError = PostDefinitionsSaveErrors[keyof PostDefinitionsSaveErrors];

export type PostDefinitionsSaveResponses = {
	/**
	 * OK
	 */
	200: CspApiDefinition;
};

export type PostDefinitionsSaveResponse = PostDefinitionsSaveResponses[keyof PostDefinitionsSaveResponses];

export type GetDirectivesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Directives';
};

export type GetDirectivesErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetDirectivesResponses = {
	/**
	 * OK
	 */
	200: Array<string>;
};

export type GetDirectivesResponse = GetDirectivesResponses[keyof GetDirectivesResponses];

export type GetDomainsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/csp/api/v1/Domains';
};

export type GetDomainsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * The authenticated user does not have access to this resource
	 */
	403: unknown;
};

export type GetDomainsResponses = {
	/**
	 * OK
	 */
	200: Array<CspDomainInfo>;
};

export type GetDomainsResponse = GetDomainsResponses[keyof GetDomainsResponses];
